version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sample-db-stream-pw"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-99m6ey9xqqf1"
s3_prefix = "sample-db-stream-pw"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
